kind: pipeline
type: docker
name: default

steps:

- name: build new docker image from tagged commit via kaniko
  image: plugins/kaniko:1.6.6
  settings:
    registry: gitea.whyservices.net
    username: whysthatso
    password:
      from_secret: registry_pass
    repo: gitea.whyservices.net/whysthatso/hacker_diet_journal
    tags: ${DRONE_TAG}
    expand-repo: true

- name: send notification to telegram
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: telegram_token
    to: 393273328
    message: >
      {{#success build.status}}
        SUCCESS build {{build.link}} triggerd by {{commit.link}} from {{commit.author}}
      {{else}}
        FAIL build {{build.link}} triggerd by {{commit.link}} from {{commit.author}}
      {{/success}}
  when:
    status:
      - success
      - failure

trigger:
  event:
  - tag
